{% set version = "2.0.0" %}

package:
  name: freexl
  version: {{ version }}

source:
  url: http://www.gaia-gis.it/gaia-sins/freexl-{{ version }}.tar.gz
  sha256: 176705f1de58ab7c1eebbf5c6de46ab76fcd8b856508dbd28f5648f7c6e1a7f0
  patches:
    - patches/makefile.vc.patch
    - patches/nmake.opt.patch
    - patches/aarch64.patch

build:
  number: 1
  run_exports:
    - {{ pin_subpackage('freexl') }}

requirements:
  build:
    - gnuconfig  # [unix]
    - {{ compiler('c') }}
    - make
  host:
    - expat
    - libiconv
    - minizip

test:
  commands:
    - test -f ${PREFIX}/lib/libfreexl.a  # [not win]

about:
  home: https://www.gaia-gis.it/fossil/freexl/index
  license: MPL-1.1
  license_file: COPYING
  summary: Extract valid data from within an Excel

extra:
  recipe-maintainers:
    - akrherz
    - ocefpaf
    - msarahan
